#!/bin/bash
# List of files with their relative paths
FILES=(
"public/index.html"
"public/index.js"
"public/modal.js"
"public/virtue.js"
"server.js"

  )
echo "Running: mcp"
printf "%s\n" "${FILES[@]}"
mcp "${FILES[@]}" > relevant_code.h
